# Generated by Django 5.1.6 on 2025-03-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_shipping_method_remove_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('validation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=50)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('card_issuer_country', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('valid', 'Valid'), ('failed', 'Failed')], default='valid', max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.order')),
            ],
        ),
    ]
