# Generated by Django 5.1.6 on 2025-04-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_quantity_sold', models.PositiveIntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margins', to='products.product')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('product', 'month', 'year')},
            },
        ),
    ]
