# Generated by Django 5.1.6 on 2025-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_profitmargin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTotalProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
